.TH LINEAK_XOSDPLUGIN 1 "December 23, 2003"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
lineak_xosdplugin \- On Screen Display plugin for the lineakd daemon 

.SH "DESCRIPTION"
LinEAK, Linux support for Easy Access and Internet Keyboards, features X11
support, windowmanager independence, ability to configure all keys through GUI
or .conf file, volume control and sound controls. 

This plugin contains an interface to the XOSD display method to provide visual feedback
when a user presses a key.
.PP
lineakd is the daemon that runs in the background of an X session and listens
to incoming events from multimedia buttons.

.SH Requirements. 
The xosd plugin requires the following to be added to your configuration file:
Display_plugin = xosd
.TP
The plugin also understands the following config file directives:
.TP
.B Display_font - This needs to be set to a font with an X style name. The default font is: "-adobe-helvetica-bold-r-normal-*-*-240-*-*-p-*-*-*"
.TP
.B Display_color - This needs to be set to a numeric color identifier. You can get a color identifier from a program like kcolorchooser. The default color is: "0aff00"
.TP
.B Display_timeout - This is the amount of time that the display stays on the screen in seconds. The default is 3 seconds.
.TP
.B Display_pos - This is the horizonal position of the display. Valid values are: top, middle or bottom. The default is bottom.
.TP
.B Display_align - This is the vertical alignment of the display. Valid values are: left, center or right. The default is center.
.TP
.B Display_hoffset - This is a number in pixels to offset the horizontal positioning of the display with respect to the Display_pos position. The default is 0.
.TP
.B Display_voffset - This is a number in pixels to offset the vertical positioning of the display with respect to the Display_align alignment. The default is 50.
.TP
.B Display_soffset - This is a number in pixels to offset the drop shadowing for the display text. The default is 1.

.SH FILES
.TP
.I $HOME/.lineak/lineakd.conf
Personal configuration file.
.SH SEE ALSO
lineakd(1),
lineak_kdeplugins(1),
lineak_defaultplugin(1).
.SH AUTHOR
.B lineak_xosdplugin
was written by Sheldon Lee-Wen <leewsb@hotmail.com>. 
