/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <stdio.h>

#include "interface.h"
#include "support.h"

#include <keytouch.h>
#include <keyboard_config.h>
#include <config.h>
#include <set_data.h>

KEYBOARD_CONFIG	current_keyboard_config;
KEYBOARD_LIST	keyboard_list;
XMODMAP_LIST	xmodmap_list;
PLUGIN_LIST	plugin_list;
PREFERENCES	preferences;

int
main (int argc, char *argv[])
{
#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	printf ("gettext ON: %s %s\n", GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
#endif
	
	gtk_set_locale ();
	gtk_init (&argc, &argv);
	
	/* Copy the missing configuration files to the ~/.keytouch */
	system ("mkdir ~/.keytouch; cp -R -i --reply=no " PACKAGE_DATA_DIR  "/" PACKAGE "/config/* ~/.keytouch/");
	
	read_config (&current_keyboard_config, &keyboard_list, &preferences);
	read_plugin_list (&plugin_list);
	init_main_window (&current_keyboard_config, &plugin_list, preferences);
}

